import assert from 'node:assert/strict';
import {combineConnections,bridgeLookup,validateBridge,bridgeLabel,bridgeEditions} from '../web/cross-domain.mjs';
import {loadReading} from '../web/reading.mjs';
import {target,refine,focusMap} from '../web/query.mjs';
const row={cross_domain:true,neighbor_domain:'fsc',neighbor_id:'fi',neighbor_law:'금융규정',neighbor_kind:'article',neighbor_jo:'2',neighbor_ref:'제2조',direction:'forward',source_id:'fx',target_id:'fi',source_ref:'제1조제2항',source_granularity:'block',source_scope:{scopes:[[['1','2','',''],['1','2','',''],-1]]},kind:'article',neighbor_sectors:['banking'],status:'exact'};
const entry={id:'fi',name:'금융규정',domain:'fsc',effective:'20260901',file:{url:'finance-body'}};
const b={kind:'forex-finance-bridge',schema:1,domain:'forex',peer:'fsc',editions:{forex:'20260921',fsc:'20260917'},entries:[entry],laws:{fx:{'1':{rows:[row],suppressed:['old'],resolved_issues:['recovered']}}},broad:{}};
const manifest={domains:[{id:'forex',built_at:'20260921'},{id:'fsc',built_at:'20260917'}]},catalog={built_at:'20260921',laws:[{id:'fx'}]};
assert.equal(validateBridge(b,'forex',manifest,catalog),b);
assert.throws(()=>validateBridge(b,'tax',manifest,catalog));
assert.throws(()=>validateBridge({...b,editions:{forex:'20250101'}},'forex',manifest,catalog));
assert.throws(()=>validateBridge({...b,entries:[{...entry,domain:'tax'}]},'forex',manifest,catalog));
const detail={rows:[],external:[{evidence_id:'old'},{evidence_id:'uncollected'}],issues:[{raw:'recovered'},{raw:'unresolved'}]};
const original=JSON.stringify(detail),combined=combineConnections(detail,[],b,'fx','1');
assert.equal(combined.rows.length,1);assert.equal(combined.external.length,1);assert.equal(combined.issues.length,1);assert.equal(JSON.stringify(detail),original);
assert.equal(combineConnections(detail,[],b,'fx','1',false).external.length,2);
assert.equal(combineConnections(detail,[],null,'fx','1').rows.length,0);
assert.equal(refine(combined.rows,target('제1조제1항')).length,0);
assert.equal(refine(combined.rows,target('제1조제2항')).length,1);
const ownLookup=new Map([['fx',{id:'fx',domain:'forex'}]]),lookup=bridgeLookup(ownLookup,b);
assert.equal(ownLookup.size,1);assert.equal(lookup.size,2);
assert.match(bridgeLabel(row),/금융 \/ 은행/);
const currentDoc={meta:{id:'fx',domain:'forex'},articles:[]},state={law:'fx',reference:'제1조'};
const stateBefore=JSON.stringify(state);
const loaded=await loadReading({id:'fi',jo:'2'},{catalog,lookup,currentDoc,read:async ref=>{
 assert.equal(ref.url,'finance-body');return {meta:entry,articles:[{jo:'2',text:'실제 수집 본문'}]};
}});
assert.equal(loaded.article.text,'실제 수집 본문');assert.equal(currentDoc.meta.id,'fx');assert.equal(JSON.stringify(state),stateBefore);
await assert.rejects(loadReading({id:'unknown',jo:'2'},{catalog,lookup,currentDoc,read:async()=>{throw Error('must not fetch');}}));
await assert.rejects(loadReading({id:'fi',jo:'2'},{catalog,lookup,currentDoc,read:async()=>({meta:{id:'fi',domain:'tax'},articles:[]})}));
const missing=await loadReading({id:'fi',jo:'99'},{catalog,lookup,currentDoc,read:async()=>({meta:entry,articles:[{jo:'2'}]})});
assert.equal(missing.article,undefined);assert.equal(missing.requestedJo,'99');
const map=focusMap([row],{id:'fx',name:'외환규정',label:'외환규정'},target('제1조'),{nodes:[],links:[]},lookup);
assert.equal(map.nodes[0].web_law,'fx');assert.equal(map.nodes[1].web_law,'fi');assert.match(map.nodes[1].status,/분야 밖/);
const annex=focusMap([{...row,annex_unanalyzed:true,neighbor_kind:'annex',neighbor_jo:'별표 4-1'}],{id:'fx',name:'외환규정'},target('제1조'),{},lookup);
assert.equal(annex.nodes[1].web_law,'');
console.log('Cross-domain browser logic checks passed');

// Same independent-reader behavior for procurement/public institutions.
const contractRow={...row,neighbor_domain:'public_institutions',neighbor_sectors:[]};
const contractEntry={...entry,domain:'public_institutions'};
const contract={...b,kind:'procurement-public-bridge',domain:'procurement',peer:'public_institutions',editions:{procurement:'20260919',public_institutions:'20260921'},entries:[contractEntry],laws:{fx:{'1':{rows:[contractRow],suppressed:[],resolved_issues:[]}}}};
const contractManifest={domains:[{id:'procurement',built_at:'20260919'},{id:'public_institutions',built_at:'20260921'}]};
assert.equal(validateBridge(contract,'procurement',contractManifest,{...catalog,built_at:'20260919'}),contract);
assert.match(bridgeLabel(contractRow),/공공기관/);
assert.match(bridgeEditions(contract),/조달계약 20260919, 공공기관 20260921/);
assert.throws(()=>validateBridge({...contract,kind:'forex-finance-bridge'},'procurement',contractManifest,{...catalog,built_at:'20260919'}));
assert.equal(combineConnections(detail,[],contract,'fx','1',false).rows.length,0);
const isolated=await loadReading({id:'fi',jo:'2'},{catalog,lookup:bridgeLookup(ownLookup,contract),currentDoc,read:async()=>({meta:contractEntry,articles:[{jo:'2',text:'공공기관 수집 본문'}]})});
assert.equal(isolated.article.text,'공공기관 수집 본문');
assert.equal(currentDoc.meta.id,'fx');assert.equal(JSON.stringify(state),stateBefore);
