import {test,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {gzipSync} from 'node:zlib';
import {createHash} from 'node:crypto';
import {data,cached,saveAll,clearSaved,configureStorage} from '../web/store.mjs';

const files=new Map(),saved=new Map();let downloads=0,offline=false;
globalThis.location={href:'https://example.test/law-orbit/'};
globalThis.caches={open:async()=>({match:async url=>saved.get(String(url))?.clone(),put:async(url,r)=>saved.set(String(url),r.clone()),delete:async url=>saved.delete(String(url))}),delete:async()=>{saved.clear();return true;}};
globalThis.fetch=async url=>{if(offline)throw Error('offline');downloads++;const bytes=files.get(new URL(url).pathname.split('/').at(-1));return new Response(bytes||'missing',{status:bytes?200:404});};
function asset(value){const raw=gzipSync(JSON.stringify(value)),sha256=createHash('sha256').update(raw).digest('hex'),ref={url:`data/${sha256}.json.gz`,bytes:raw.length,sha256};files.set(sha256+'.json.gz',raw);return {ref,raw};}
function fixture(){const a=asset({body:'제32조 🌠 원문',details:{nested:true}}),b=asset({body:'제60조 원문'});const groups={};for(const {ref,raw} of [a,b]){const k=ref.sha256.slice(0,2);groups[k]??={};groups[k][ref.sha256]=raw.toString('base64');}const buckets=Object.fromEntries(Object.entries(groups).map(([k,entries])=>[k,asset({kind:'law-orbit-small-files',schema:1,entries}).ref]));for(const {ref} of [a,b])files.delete(ref.sha256+'.json.gz');return {a,b,config:{schema:1,threshold:8192,prefix_chars:2,buckets}};}
beforeEach(async()=>{await clearSaved();configureStorage(null);files.clear();downloads=0;offline=false;});
test('legacy storage still verifies, reads and caches data',async()=>{const {ref}=asset({body:'원문'});assert.equal((await data(ref)).body,'원문');assert.equal(await cached(ref),true);assert.equal(downloads,1);});
test('packed members preserve contents and concurrent requests share a pack fetch',async()=>{const {a,config}=fixture();configureStorage(config);const result=await Promise.all([data(a.ref),data(a.ref)]);assert.deepEqual(result[0],{body:'제32조 🌠 원문',details:{nested:true}});assert.equal(downloads,1);assert.equal(await cached(a.ref),true);});
test('packed data works offline after memory reset and retains cache availability',async()=>{const {a,config}=fixture();configureStorage(config);await saveAll([a.ref],()=>{});const bytes=[...saved.entries()].map(([k,v])=>[k,v.clone()]);await clearSaved();for(const [k,v] of bytes)saved.set(k,v);configureStorage(config);offline=true;assert.equal(await cached(a.ref),true);assert.match((await data(a.ref)).body,/제32조/);});
test('existing verified standalone cache avoids redownloading a packed member',async()=>{const {a,config}=fixture();saved.set(new URL(a.ref.url,location.href).href,new Response(a.raw));configureStorage(config);offline=true;assert.match((await data(a.ref)).body,/원문/);assert.equal(downloads,0);});
test('tampering the pack or member cannot pass checksum verification',async()=>{const {a,config}=fixture();const prefix=a.ref.sha256.slice(0,2),pack=config.buckets[prefix];files.set(pack.sha256+'.json.gz',Buffer.from('tampered'));configureStorage(config);await assert.rejects(data(a.ref),/검증/);const malformed=asset({kind:'law-orbit-small-files',schema:1,entries:{[a.ref.sha256]:gzipSync('{"body":"different"}').toString('base64')}});config.buckets[prefix]=malformed.ref;configureStorage(config);await assert.rejects(data(a.ref),/검증/);});
test('missing members, invalid config and unsafe paths fail explicitly',async()=>{const {a,config}=fixture();config.buckets[a.ref.sha256.slice(0,2)]=asset({kind:'law-orbit-small-files',schema:1,entries:{}}).ref;configureStorage(config);await assert.rejects(data(a.ref),/항목/);assert.throws(()=>configureStorage({...config,threshold:100}),/형식/);await assert.rejects(data({...a.ref,url:'https://elsewhere.test/x'}),/경로/);});
test('clearing storage removes packed availability and cancellation stops saving',async()=>{const {a,config}=fixture();configureStorage(config);await data(a.ref);await clearSaved();assert.equal(await cached(a.ref),false);assert.equal(await saveAll([a.ref],()=>{},{aborted:true}),0);});
