"""Small official-wording regressions from the 2026-10-04 tax citation audit.

No corpus, network, credentials, or AI is required. Expected scopes below are
hand annotations of the quoted text; they are not generated by the parser.
"""
import unittest
from unittest.mock import patch

from core.article_relations import analyze_article_relations
from core.citation_parser import parse_citations, effective_law_name
from core.citation_scope import parse_scope, parse_target, classify
from core.universe_builder import build_tax_universe
from scripts.test_law_universe import article, law


def graph_for(name, jo, text, targets):
    source = article(jo, [(f'제{jo}조', f'제{jo}조(출발 조문)'), ('원문 표본', text)])
    docs = {name: law(name, 'tax', [source])}
    for target_name, numbers in targets.items():
        doc = docs.setdefault(target_name, law(target_name, 'tax', []))
        doc['articles'].extend(article(n, [(f'제{n}조', f'제{n}조(대상 조문)')]) for n in numbers)
    graph = build_tax_universe(dict(built_at='fixture', laws=list(docs.values())))
    return [e for e in graph['edges'] if e['source_law'] == name and e['source_jo'] == jo], source


class TaxCitationAuditTests(unittest.TestCase):
    def assert_raw(self, edges, article_text):
        for edge in edges:
            self.assertEqual(article_text[edge['source_start']:edge['source_end']], edge['cite_raw'])

    def test_income_70_paragraph_2_keeps_na_mok(self):
        text = '② 해당 과세기간에 분리과세 주택임대소득 및 제127조제1항제6호나목의 소득이 있는 경우에도 제1항을 적용한다.'
        edges, source = graph_for('소득세법', '70', text, {'소득세법': ['127']})
        self.assertEqual([(e['target_ref'], e['cite_raw']) for e in edges],
                         [('제127조제1항제6호나목', '제127조제1항제6호나목')])
        self.assertEqual(parse_scope(edges[0]['cite_raw']).scopes[0].start.path, ('127', '1', '6', '나'))
        self.assertEqual(classify(edges[0]['cite_raw'], parse_target('제127조제1항제6호가목'))[0], 'disjoint')
        self.assert_raw(edges, source['text'])

    def test_income_21_item_21_keeps_enumerated_mok(self):
        text = '21. 제20조의3제1항제2호나목 및 다목의 금액을 그 소득의 성격에도 불구하고 연금외수령한 소득'
        edges, source = graph_for('소득세법', '21', text, {'소득세법': ['20의3']})
        self.assertEqual({e['target_ref'] for e in edges}, {'제20조의3제1항제2호나목', '제20조의3제1항제2호다목'})
        self.assertEqual({e['cite_raw'] for e in edges}, {'제20조의3제1항제2호나목 및 다목'})
        self.assertEqual([s.start.path for s in parse_scope(edges[0]['cite_raw']).scopes],
                         [('20의3', '1', '2', '나'), ('20의3', '1', '2', '다')])
        self.assert_raw(edges, source['text'])

    def test_corporate_18_item_8_ga_does_not_cover_na(self):
        text = '가. 제16조제1항제2호가목에 해당하지 아니하는 자본준비금'
        edges, source = graph_for('법인세법', '18', text, {'법인세법': ['16']})
        self.assertEqual([(e['target_ref'], e['cite_raw']) for e in edges],
                         [('제16조제1항제2호가목', '제16조제1항제2호가목')])
        self.assertEqual(classify(edges[0]['cite_raw'], parse_target('제16조제1항제2호나목'))[0], 'disjoint')
        self.assert_raw(edges, source['text'])

    def test_corporate_18_2_keeps_na_after_explicit_self_law(self):
        text = '6. 「자산재평가법」 제28조제2항을 위반하여 이 법 제16조제1항제2호나목에 따른 재평가적립금을 감액하여 지급받은 수입배당금액'
        edges, source = graph_for('법인세법', '18의2', text, {'법인세법': ['16'], '자산재평가법': ['28']})
        selected = [e for e in edges if e['target_law'] == '법인세법']
        self.assertEqual([(e['target_ref'], e['cite_raw']) for e in selected],
                         [('제16조제1항제2호나목', '이 법 제16조제1항제2호나목')])
        self.assert_raw(edges, source['text'])

    def test_corporate_decree_24_keeps_ra_to_ba_range(self):
        text = '사. 사용수익기부자산가액: 금전 외의 자산을 국가 또는 지방자치단체, 법 제24조제2항제1호라목부터 바목까지의 규정에 따른 법인 또는 이 영 제39조제1항제1호에 따른 법인에게 기부한 후 그 자산을 사용하거나 그 자산으로부터 수익을 얻는 경우 해당 자산의 장부가액'
        edges, source = graph_for('법인세법 시행령', '24', text, {'법인세법': ['24'], '법인세법 시행령': ['39']})
        selected = [e for e in edges if e['target_law'] == '법인세법']
        self.assertEqual([(e['target_ref'], e['cite_raw']) for e in selected],
                         [('제24조제2항제1호라목', '법 제24조제2항제1호라목부터 바목까지')])
        scope = parse_scope(selected[0]['cite_raw']).scopes[0]
        self.assertEqual((scope.start.path, scope.end.path, scope.axis),
                         (('24', '2', '1', '라'), ('24', '2', '1', '바'), 3))
        # The existing scope engine keeps Korean-letter ranges reviewable.
        # Restore their endpoints without silently claiming a resolved interval.
        self.assertIn('목 범위', parse_scope(selected[0]['cite_raw']).review_reason)
        self.assert_raw(edges, source['text'])

    def test_explicit_named_relative_and_deictic_patterns_keep_the_same_fields(self):
        cases = [
            ('「법인세법」 제16조제1항제2호가목', '법인세법'),
            ('법인세법 제16조제1항제2호가목', '법인세법'),
            ('「법인세법」 제15조 및 같은 법 제16조제1항제2호가목', '법인세법'),
            ('「법인세법」 제16조제2항 및 같은 조 제1항제2호가목', '법인세법'),
            ('법 제16조제1항제2호가목', '법인세법'),
        ]
        for text, owner in cases:
            with self.subTest(text=text):
                cites = [c for c in parse_citations(text) if c.mok == '가']
                self.assertEqual(len(cites), 1)
                cite = cites[0]
                self.assertEqual((cite.jo, cite.jo_sub, cite.hang, cite.ho, cite.mok), ('16', '', '1', '2', '가'))
                self.assertEqual(effective_law_name(cite, '법인세법 시행령'), owner)
                self.assertEqual(text[slice(*cite.span)], cite.raw)
                self.assertTrue(cite.raw.endswith('가목'))

    def test_named_law_chain_continues_after_enumerated_mok(self):
        text = '「법인세법」 제24조제2항제1호나목 및 다목 및 제25조를 준용한다.'
        edges, _ = graph_for('소득세법', '21', text, {'법인세법': ['24', '25']})
        self.assertEqual({(e['target_law'], e['target_ref']) for e in edges},
                         {('법인세법', '제24조제2항제1호나목'), ('법인세법', '제24조제2항제1호다목'), ('법인세법', '제25조')})

    def test_branch_item_with_mok_remains_supported_by_existing_tail(self):
        text = '제14조제1항제1호의2가목을 적용한다.'
        edges, _ = graph_for('법인세법', '16', text, {'법인세법': ['14']})
        self.assertEqual([(e['target_ref'], e['cite_raw']) for e in edges],
                         [('제14조제1항제1호의2가목', '제14조제1항제1호의2가목')])

    def test_legacy_forward_and_selected_target_keep_numeric_and_korean_mok(self):
        cases = (
            ('3', '제16조제1항제2호제3목', '제10조제1항제2호제3목'),
            ('가', '제16조제1항제2호가목', '제10조제1항제2호가목'),
        )
        for mok, quote, target in cases:
            with self.subTest(mok=mok), \
                    patch('core.article_relations.graph_available', return_value=False), \
                    patch('core.article_relations.matrix_available', return_value=False):
                result = analyze_article_relations(
                    '법인세법', '10', quote + '을 적용한다.', hang='1', ho='2', mok=mok)
                self.assertEqual(result['cited'], [
                    {'법령명': '법인세법', '조문': quote, '원문': quote, '범위': False}])
                self.assertEqual(result['target_label'], target)

    def test_numeric_mok_and_intra_references_keep_legacy_behavior(self):
        cite = next(c for c in parse_citations('제10조제1항제2호제3목') if c.jo)
        self.assertEqual((cite.jo, cite.hang, cite.ho, cite.mok), ('10', '1', '2', '3'))
        intra = parse_citations('제3항 및 제2호와 제4목')
        self.assertEqual([(c.jo, c.hang, c.ho, c.mok) for c in intra],
                         [('', '3', '', ''), ('', '', '2', ''), ('', '', '', '4')])
        self.assertEqual(parse_citations('가목 및 나목, 라목부터 바목까지'), [])
        self.assertFalse(any(c.mok for c in parse_citations('제10조가목')))


if __name__ == '__main__':
    unittest.main()
